name: erlite test 
run-name: ${{ github.actor }} is testing erlite 
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job was automatically triggered by ${{ github.event_name }}."

