name: erlite test 
run-name: ${{ github.actor }} is testing erlite 
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: erlang:27.0.1
    steps:
      - uses: actions/checkout@v4
      - run: rebar3 do eunit, ct 

